### ISSUE TITLE
OS compatibility?

### ISSUE THREAD

**Issue by tukoz** [Mehni/ModSorter#3]
Looks nice Mehni! Is it Windows only or does it have some compatibility layer via unity3d?

**Comment by Mehni** [comment]
Windows only I'm afraid.

For multi OS support the following things would need to change:
- Get rid of the assumptions regarding filepaths and the way they're structured. 
    - This would be a reasonable change.
- The Ookii dialogs I use for the file selections are windows only, AFAIK. I could be wrong.
    - I only use one class of this dependency, so substituting for an alternative wouldn't be low-impact.
- Convert from .NET Framework 4.7 to .NET Core preview 3. ModSorter is a WPF application. 
    - My understanding of .NET Core preview 3 is that it is meant for cross platform code but I honestly don't know how far along that is.

**Comment by Mehni** [comment]
Looked into it a bit more.

.NET Core 3 is indeed cross-platform compatible. That does not include WPF, that remains bound to Windows. Since I'm not familiar with the Linux/Mac GUI ecosystem, it would take a lot of time/effort for me to replicate the GUI on those platforms. More than I am willing to invest.

I would happily accept a PR or fork with cross platform compatibility, but I can't justify creating that myself.

**Comment by tukoz** [comment]
Appreciated @Mehni, thank you for clarifying.

**Comment by deathbutton1** [comment]
It would be helpful to put that Linux isn't supported in the readme. It can be a bit frustrating having to download and try to run or look at the closed issues to find out whether a program will work on my OS.

**Comment by Mehni** [comment]
Sure, updated the readme.
